### ISSUE TITLE
Theme builder generated OSX .terminal file not matching original (lightened instead)

### ISSUE THREAD

**Issue by zanona** [chriskempson/base16-builder#196]
Hey guys,
I have built the OSX Ocean theme for terminal using the builder script, however, when checking it against http://chriskempson.github.io/base16/#ocean I could see that mainly, the background colour is not the same as the one shown? — Overall, mine is looking a bit ‘_washed-out_’.

![screen shot 2014-11-25 at 09 47 09](https://cloud.githubusercontent.com/assets/32017/5180847/760f6abe-7488-11e4-89b1-dcc87308fe76.png)

Am I doing something wrong?
I just have imported the `.terminal` file generated by the builder onto OSX Terminal and also have added the `.vim` file to `~/.vim/colors` and configured my `~/.vimrc` accordingly.

**Comment by Haroenv** [comment]
Why did you pair bright magenta with grey, and bright cyan with brown @zanona?

**Comment by zanona** [comment]
@Haroenv I believe this is just the way base16 ocean set colours. If you run the [ruby script](https://github.com/chriskempson/base16-builder/tree/master/templates/terminal-app) to generate  the .terminal file you will see how that reflects.

I don't really think the standard colour names have relation to how the colours are themed on ocean.

**Comment by Haroenv** [comment]
Ah yes, this changed since last time I ran it, thanks!
