### ISSUE TITLE
base16 for st terminal emulator

### ISSUE THREAD

**Issue by d3m1gd** [chriskempson/base16-builder#281]
I ported base16 from xresources to [st](http://st.suckless.org/) term as patches.
If it is of any interest, you can put a link to [my repo](https://github.com/d3m1gd/base16-st/tree/master) among other ports.

**Comment by pickfire** [comment]
+1

**Comment by pickfire** [comment]
This is duplicated, look at #245

**Comment by d3m1gd** [comment]
there is no base16-builder in my repo, only patches. But i didnt found a more apropriate place to open an issue.

To project owners, if this issue is unrelevant, feel free to close it.

**Comment by pickfire** [comment]
It seems that `st` cannot use *base16* **light** theme.

**Comment by d3m1gd** [comment]
i have no problems with light themes in `st`. Is there some particular theme causing troubles?

**Comment by pickfire** [comment]
I use light theme by applying the patch and using the base16-shell. Is there anything wrong about it?

**Comment by d3m1gd** [comment]
Cannot help you with a builder, as in my repo colors are directly converted from compiled Xresources colours and made into patches. When i apply light themes from my repo and use base16-shell, everything works fine.

**Comment by pickfire** [comment]
I think I will edit some of the `config.h` using the ones in your repo. I will have a look in it.
