### ISSUE TITLE
Emacs: base16-atelierlakeside-dark theme makes inactive buffer names unreadable

### ISSUE THREAD

**Issue by Droogans** [chriskempson/base16-builder#364]
Raising https://github.com/mkaito/base16-emacs/issues/19 here to increase visibility.

How do you account for one-off exceptions in the base-16 themes? Right now I've simply over-ridden my local copy (which I backup in its entirety to github, so this issue doesn't affect me much).

The line in question: https://github.com/chriskempson/base16-builder/blob/9b24598c08a27780f87c318e6145c1468b9880ba/templates/emacs/-dark-theme.el.erb#L45

Here's my fix:

```
   `(mode-line-buffer-id ((t (:foreground ,base0B :background nil))))
```

> before

![screen shot 2016-05-21 at 12 15 31]
(https://cloud.githubusercontent.com/assets/1214609/15449801/bb8c90fa-1f4d-11e6-96b3-46f0e25230ca.png)

> after

![screen shot 2016-05-21 at 12 16 05](https://cloud.githubusercontent.com/assets/1214609/15449804/cfe288de-1f4d-11e6-89ba-6214438bb31e.png)

In my instance, it was much simpler over-riding the value of that one section with a pre-existing color from the theme. I imagine here that it may make more sense to change that `base0E` shade of purple to look nice against the `base02`-`base06` variables instead, maybe?

**Comment by belak** [comment]
This has been changed in the updated base16 emacs repo. Changing to be base0B seems reasonable and it appears to look fine in other themes as well. Knowing my luck it'll probably break other stuff, but it's worth a shot.
